### ISSUE TITLE
A Linux port

### ISSUE THREAD

**Issue by flippette** [gluschenko/UnityDarkSkin#12]
You know what? This project has already grown to the point that some YT tutorials and even some websites have started to point to this repository. It would be a nice addition to also have a Linux port so that we can also not get our eyes burnt down during night sessions!

**Comment by mervick** [comment]
Any updates on this?

**Comment by flippette** [comment]
I don't think so. Unity ain't changing, and this tool continues to be Windows-only for the moment... I hope so.

**Comment by mervick** [comment]
Is this issue fixed? Can I use this on Linux now?

**Comment by flippette** [comment]
There are guides that utilizes binary disassembly to directly change the skin... maybe someone can automate that process?

**Comment by StefanJanssen95** [comment]
> There are guides that utilizes binary disassembly to directly change the skin... maybe someone can automate that process?

Do you have the link to those guides? I know they exist for windows but have not seen them for Linux.
