### ISSUE TITLE
Not working on version 2019.1.14f

### ISSUE THREAD

**Issue by victor871129** [gluschenko/UnityDarkSkin#14]

**Comment by gluschenko** [comment]
How to reproduce a way, when it may not work? I installed 2019.1.14f and successfully patched this version. I just interested in cases when it might go wrong :-)

![12345](https://user-images.githubusercontent.com/9298580/63976865-fb476a00-caba-11e9-93cd-dcef48ff4923.png)

**Comment by victor871129** [comment]
I dont know why, I know the exe changed the Unity.exe file. I restarted the
PC and the app theme is the light one.

**Comment by gluschenko** [comment]
Maybe your Unity.exe file is not official and modified by different way?
