### ISSUE TITLE
2019.3 support

### ISSUE THREAD

**Issue by Mrgove10** [gluschenko/UnityDarkSkin#15]
Hello,
Any plans to support unity 2019.3 ?

**Comment by gluschenko** [comment]
Yes, it will be soon

**Comment by gluschenko** [comment]
UPD: Tried to patch 2019.3.0b1 with no changes in my program. It was detected as 2019.2 and successfully switched theme.

![2019 3](https://user-images.githubusercontent.com/9298580/64078853-d8020200-cce8-11e9-8b8d-a5d9e707dc73.jpg)
