### ISSUE TITLE
Complete dark theme for Unity 2019.3 beta

### ISSUE THREAD

**Issue by tamimmirza** [gluschenko/UnityDarkSkin#18]
Basically I used the patch on Unity 2019.3 Beta 1 and it worked but it looks like this:

![Annotation 2019-09-09 000751](https://user-images.githubusercontent.com/35456031/64493191-643a9900-d296-11e9-9785-8c8c176500d5.jpg)

Whereas the official dark mode looks like so:

![unity-beta-dark-cust](https://user-images.githubusercontent.com/35456031/64493194-774d6900-d296-11e9-9eab-79134568c5ca.jpg)

The title bar on the official dark mode also turns black when the theme has been changed to dark. Is there anyway to implement this in your "fix"?

**Comment by gluschenko** [comment]
I did not find a video where the title bar is not white. Only white bar, provided by native Win32 API: https://youtu.be/yAkueCWg09k?t=228

Once you can do now -- setup title bar color in Windows Settings:
![Windows-10-show-color-on-title-bar](https://user-images.githubusercontent.com/9298580/65631387-1a64e900-dfe0-11e9-914c-8a9888509e91.png)
