### ISSUE TITLE
Please Support Unity2019.2.6f1

### ISSUE THREAD

**Issue by k-k-s-s** [gluschenko/UnityDarkSkin#20]
Could you support Unity2019.2.6f1? thank you.

**Comment by gluschenko** [comment]
Yes

**Comment by JoNax97** [comment]
Hey apparently something happened in 2019.2.6+ 
The exe is correctly patched and says it's alright, but Unity is stuck on white theme :(

**Comment by Gazenvagin** [comment]
>The exe is correctly patched and says it's alright, but Unity is stuck on white theme :(
такая же фигня :)

**Comment by Gazenvagin** [comment]
2019.2.13 - Could not to switch theme
