### ISSUE TITLE
PLZ Compile it for me

### ISSUE THREAD

**Issue by chakibchemso** [gluschenko/UnityDarkSkin#21]
HI
Can u jst send me a compiled release (the .exe file only)

first i havent vs
second i cant download it now (my internet is f***** up and i m using vscode instead)
third plz cz i hate the gray color (disgusting)

**Comment by gluschenko** [comment]
[Release.zip](https://github.com/Gluschenko/UnityDarkSkin/files/3881426/Release.zip)

**Comment by chakibchemso** [comment]
MY MAN
THANKS FOR THAT
