### ISSUE TITLE
MY EYES STILL BURNING

### ISSUE THREAD

**Issue by chakibchemso** [gluschenko/UnityDarkSkin#22]
DIDNT WORK FOR 2019.3.0B1 IT SAYS THEME SWITCHED BUT THE EDITOR STILL GRAY
AND MY EYES STILL BURNING
![image](https://user-images.githubusercontent.com/41765106/69478069-463cf900-0dee-11ea-84a8-0d711973be19.png)
![image](https://user-images.githubusercontent.com/41765106/69478077-679de500-0dee-11ea-927e-3c88fb288eaf.png)

**Comment by chakibchemso** [comment]
ok i fixed
turning a hex value from 75 to 74 and deleting the user skin value from the windows registry
works 😀
![image](https://user-images.githubusercontent.com/41765106/69480323-e99a0800-0e06-11ea-9506-9bf9570dbb4f.png)

**Comment by Lijunsen** [comment]
> ok i fixed
> turning a hex value from 75 to 74 and deleting the user skin value from the windows registry
> works 😀
> ![image](https://user-images.githubusercontent.com/41765106/69480323-e99a0800-0e06-11ea-9506-9bf9570dbb4f.png)

Could you tell me how to do it？

**Comment by chakibchemso** [comment]
yo! sry this was closed so didn't get a not. somehow...
ya still need help?

**Comment by Lijunsen** [comment]
> yo! sry this was closed so didn't get a not. somehow...
> ya still need help?

I had already find the other way,thanks
