### ISSUE TITLE
It does not work!

### ISSUE THREAD

**Issue by Lijunsen** [gluschenko/UnityDarkSkin#23]
It always report an Error "This version is not supported.Try another version of unity",what ever witch version.(I try the version of 2019.2.8f1 and 2019.2.14f1,and Hub version is 2.21.)

**Comment by gluschenko** [comment]
Latest commit should be work on 2019.2.14f1. Did you updated the repo?

**Comment by Lijunsen** [comment]
> Latest commit should be work on 2019.2.14f1. Did you updated the repo?

What mean of the repo？

First of all,I tried the 2019.2.14f downloaded in the Hub,It's the location:
![image](https://user-images.githubusercontent.com/43627428/70104872-5cfb0f80-167a-11ea-98ac-bce98cb8bce5.png)

And I use the APP to select the unity.exe:
![image](https://user-images.githubusercontent.com/43627428/70105350-85373e00-167b-11ea-9c91-88435deeb130.png)

It report the Error:
![image](https://user-images.githubusercontent.com/43627428/70105406-a8fa8400-167b-11ea-9bdf-39dec534252a.png)

Then if I enforce to select the version,It report another Error:
![image](https://user-images.githubusercontent.com/43627428/70105521-fecf2c00-167b-11ea-87ff-e68b550f4a0f.png)

Next if I click the button of "SWITCH THEME",the unity.exe would be broken and could not be open:
![image](https://user-images.githubusercontent.com/43627428/70105629-5e2d3c00-167c-11ea-818e-cf00ac9fde51.png)

Finally,I downloaded another unity on the official website(https://unity.cn/releases),the version is 2019.2.8f1 and 2019.2.14f1. And I install in the default location, It still so.
![image](https://user-images.githubusercontent.com/43627428/70106273-21fadb00-167e-11ea-9e6c-6bf70a320241.png)

I upload an unity.exe,could you resolve it? PLZ.
https://github.com/Lijunsen/An-untiy.exe

**Comment by Gazenvagin** [comment]
чет не работает 
- 2019.2.14 - не определяет как и 2019.2 
- 2019.3 - вроде как меняет, но реально остается как и раньше лайт-шкурка
проверял app и консоль, заново все репу перекачивал

**Comment by Gazenvagin** [comment]
if don't work after change theme to dark 
when:
Step 1 : Open Regedit
Step 2 : Go to HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X
Step 3 : Ctrl+F type “UserSkin” hit enter
Step 4 : right click then modify value data(Decm) from 0 to 1
restart windows

**Comment by Lijunsen** [comment]
> if don't work after change theme to dark
> when:
> Step 1 : Open Regedit
> Step 2 : Go to HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X
> Step 3 : Ctrl+F type “UserSkin” hit enter
> Step 4 : right click then modify value data(Decm) from 0 to 1
> restart windows

Hey thanks guy. But this way still does not work, I have already give up. ( T v T )

![image](https://user-images.githubusercontent.com/43627428/70401601-5e0db180-1a6b-11ea-9268-17226fc864a6.png)

**Comment by yukuyoulei** [comment]
> if don't work after change theme to dark
> when:
> Step 1 : Open Regedit
> Step 2 : Go to HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X
> Step 3 : Ctrl+F type “UserSkin” hit enter
> Step 4 : right click then modify value data(Decm) from 0 to 1
> restart windows

It works for me, and FYI, no need to restart windows, just restart the Unity.
Thanks a lot.

**Comment by nekolyst** [comment]
> if don't work after change theme to dark
> when:
> Step 1 : Open Regedit
> Step 2 : Go to HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X
> Step 3 : Ctrl+F type “UserSkin” hit enter
> Step 4 : right click then modify value data(Decm) from 0 to 1
> restart windows

For me, it works on 2019.2.15f1.

**Comment by gluschenko** [comment]
> > if don't work after change theme to dark
> > when:
> > Step 1 : Open Regedit
> > Step 2 : Go to HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X
> > Step 3 : Ctrl+F type “UserSkin” hit enter
> > Step 4 : right click then modify value data(Decm) from 0 to 1
> > restart windows
> 
> For me, it works on 2019.2.15f1.

Ok. I'll try to add register editor soon.

**Comment by kaninhot004** [comment]
> if don't work after change theme to dark
> when:
> Step 1 : Open Regedit
> Step 2 : Go to HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X
> Step 3 : Ctrl+F type “UserSkin” hit enter
> Step 4 : right click then modify value data(Decm) from 0 to 1
> restart windows

This worked for me. Thank you!

(Do it after patched Dark Theme)
