### ISSUE TITLE
How do I compile it?

### ISSUE THREAD

**Issue by vargblut** [gluschenko/UnityDarkSkin#24]
I downloaded and opened the folder in Visual Studio, but, when I click compile, it doesn't work, I try to run, but nothing ...

**Comment by flippette** [comment]
Can you provide more details, please?

**Comment by gluschenko** [comment]
![IMG_20191215_100231](https://user-images.githubusercontent.com/9298580/70859277-26e34880-1f22-11ea-871a-1faba173899c.jpg)

**Comment by vargblut** [comment]
I have Visual Studio 2019 and .Net Framework installed, but when i download the ZIP archive and opened the Visual Studio, i push in Build in VS and the console show ERROR all time.

**Comment by gluschenko** [comment]
What is this error or errors?

**Comment by vargblut** [comment]
1>------ Build started: Project: UnityDarkSkin.Lib, Configuration: Debug|AnyCPU ------
  UnityDarkSkin.Lib -> C:\Users\Jormun\Desktop\UnityDarkSkin-master\UnityDarkSkin.Lib\bin\Debug\UnityDarkSkin.Lib.dll
2>------ Build started: Project: UnityDarkSkin, Configuration: Debug|AnyCPU ------
3>------ Build started: Project: UnityDarkSkin.App, Configuration: Debug|AnyCPU ------
  UnityDarkSkin -> C:\Users\Jormun\Desktop\UnityDarkSkin-master\UnityDarkSkin\bin\Debug\Unity Dark Skin Console.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.WindowsAPICodePack, Version=1.1.3.3, Culture=neutral, PublicKeyToken=8985beaab7ea3f04, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.WindowsAPICodePack.Shell, Version=1.1.3.3, Culture=neutral, PublicKeyToken=8985beaab7ea3f04, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
C:\Users\Jormun\Desktop\UnityDarkSkin-master\UnityDarkSkin.App\Core\IOHelper.cs(7,17,7,35): error CS0234: The type or namespace name 'WindowsAPICodePack' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
C:\Users\Jormun\Desktop\UnityDarkSkin-master\UnityDarkSkin.App\Core\IOHelper.cs(29,39,29,59): error CS0246: The type or namespace name 'CommonOpenFileDialog' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by gluschenko** [comment]
You need manually install WindowsAPICodePack into project, using NuGet package manager:
https://www.nuget.org/packages/Microsoft-WindowsAPICodePack-Core/
https://www.nuget.org/packages/Microsoft-WindowsAPICodePack-Shell/

Tutorial how to use NuGet: https://dzone.com/articles/install-nuget-packages-in-visual-studio (pic related)

![Install NuGet packages in Visual Studio4](https://user-images.githubusercontent.com/9298580/70870036-d8748f00-1f9f-11ea-9c01-e7c23bc51d9d.png)

![Install NuGet packages in Visual Studio5](https://user-images.githubusercontent.com/9298580/70870035-d8748f00-1f9f-11ea-8a6f-cc3a29cf2635.png)

**Comment by vargblut** [comment]
Thanks now it works perfectly.
