### ISSUE TITLE
Bump to .net 4.8 & c# V8

### ISSUE THREAD

**Issue by Mrgove10** [gluschenko/UnityDarkSkin#25]
We could upgrade the .net framwork version to stay up to date

**Comment by gluschenko** [comment]
What do you think about NET Core 3?

**Comment by Mrgove10** [comment]
.net core 3 would be awesome, it would allow to make the first steps towards #12 .

I am just unsure about WPF : https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework

I don't know if it is super compatible.

**Comment by StefanJanssen95** [comment]
Maybe look at https://github.com/AvaloniaUI/Avalonia.
Its a multiplatform UI framework for .NET Framework. If you are interested I am open to port the wpf parts to Avalonia.

**Comment by gluschenko** [comment]
> Maybe look at https://github.com/AvaloniaUI/Avalonia.
> Its a multiplatform UI framework for .NET Framework. If you are interested I am open to port the wpf parts to Avalonia.

Yeap, it was in TODO list, but crossplatform feature is not usefull, while there is no patch for  Unity on Linux / Mac. I tried to modify Editor on Ubuntu, but without success. Maybe migration to Avalonia now becomes helpfull in future.

**Comment by StefanJanssen95** [comment]
> There are guides that utilizes binary disassembly to directly change the skin... maybe someone can automate that process?

_Originally posted by @FlipperCanoe163 in https://github.com/Gluschenko/UnityDarkSkin/issues/12#issuecomment-563327047_

This comment does seem to suggest there are guides for Linux which work. Maybe @FlipperCanoe163 can share it so we can check it out?
