### ISSUE TITLE
Create executables for the releases

### ISSUE THREAD

**Issue by Mrgove10** [gluschenko/UnityDarkSkin#27]
Add the ".exe" files to the releases so we can just download it without having to build it ourselfs each time.

**Comment by gluschenko** [comment]
Ok

**Comment by tamimmirza** [comment]
> Add the ".exe" files to the releases so we can just download it without having to build it ourselfs each time.

This is a fantastic idea and quite simple

**Comment by gluschenko** [comment]
Work is done!

https://github.com/Gluschenko/UnityDarkSkin/releases/tag/2020.02
