### ISSUE TITLE
Unity switched from light to dark theme while using it and now it won't go back.

### ISSUE THREAD

**Issue by asusralis** [gluschenko/UnityDarkSkin#28]
Like the title says, I was using the dark theme for a few weeks now. I created a build - that I've done many times before - and the editor randomly switched to light after building.

I opened up the application and it said I was on the dark theme. I switched back from light to dark again but it was still on the light theme. I reinstalled that specific Unity version but I have the same problem! I'm on 2019.3.0f6.

**Comment by gluschenko** [comment]
Editor changed theme immediately or after relaunch?

**Comment by asusralis** [comment]
Immediately after the build was done while the editor was running. Parts of the build window became light and when I closed it the entire editor turned light.

**Comment by darthgelum** [comment]
Same thing, but switched from dark to light. 2019.2.18f1

**Comment by MostHated** [comment]
When this happens you have to change HKEY_CURRENT_USER->Software->Unity Technologies->Unity Editor 5.X. Search for "UserSkin" and change the 0 back to a 1.
