### ISSUE TITLE
Updated Hub today and theme switcher stopped working.

### ISSUE THREAD

**Issue by Supergeek** [gluschenko/UnityDarkSkin#34]
Re-ran the patcher a few times and it no longer switches modes. 

_Edit to add a few more details._ 

I've been running successfully patched 2019.3.0f6 for a while. The Hub prompted me to restart it to apply an update, so I did. After that, the dark theme was disabled, and running the patcher to flip it either way does not work. The Unity.exe file has not been updated, and using my backup exe doesn't help. 

I can't run the Editor without it launching the Hub. I don't know if this is previously known behavior or not. Something changed; maybe the Hub itself has some kind of mitigation for the mod.

**Comment by Agoxandr** [comment]
@Supergeek I have the same issue. They must have changed something.

**Comment by Agoxandr** [comment]
Some actions reset a registry entry. If you do https://github.com/Gluschenko/UnityDarkSkin/issues/23#issuecomment-562925547 and have your exe patched it will work again.

**Comment by Supergeek** [comment]
Thanks!

UserSkin was 0, but there was a UserSkin_h23982395629 (some long hash number) that was 0. Changing it to 1 fixed it. I didn't even have to restart Windows to get it to work.
