### ISSUE TITLE
2020.1.0b3 Support

### ISSUE THREAD

**Issue by yigitkahraman** [gluschenko/UnityDarkSkin#35]
App or Console can't find signature.

**Comment by yigitkahraman** [comment]
Any news on this issue? It goes all for 2020.1.0betas.

**Comment by frycojsd** [comment]
Worked for Unity 2020.1. 0b5 (64-bit) https://kosro.de/unity-dark-theme/

**Comment by yigitkahraman** [comment]
this repo has a more elegant solution, if you look into source.
btw can confirm it works for **19.3.14f1**
