### ISSUE TITLE
Unity 2019.3.7f1 not working

### ISSUE THREAD

**Issue by CyberBison** [gluschenko/UnityDarkSkin#36]
Tried to install the dark theme for 2019.3.7f1, installer worked but the theme didn't changed.

**Comment by aprius** [comment]
try this : https://github.com/Gluschenko/UnityDarkSkin/issues/23#issuecomment-562925547

**Comment by aprius** [comment]
It still work for me

**Comment by CyberBison** [comment]
That worked, thank you !
