### ISSUE TITLE
Please add support for Hub 2.0.0 & 2019.1.2f1 

### ISSUE THREAD

**Issue by nukadelic** [gluschenko/UnityDarkSkin#7]
Developing custom editors to extend unity functionality i found this tool very useful. Sadly after I installed unity Hub it stopped working, i tied stopping Hub after opening the project but it keeps it alive as long as unity is opened.

**Comment by nukadelic** [comment]
Found a solution, you have to delete the following [folders](https://www.reddit.com/r/Unity3D/comments/a687ua/help_needed_unity_20183_dark_editor_theme/ej7ae3k?utm_source=share&utm_medium=web2x) in registry:
"HKEY_CURRENT_USER\Software\Unity Technologies"
"HKEY_CURRENT_USER\Software\Unity"

**Comment by flippette** [comment]
This is fixed, m8. Close this issue!
